origin_base_url = "https://<example>"
bench_base_url = "https://<example>"
stream = true

[headers]
origin = { name = "key", value = "xxxx" }
bench = { name = "key", value = "xxxx" }

[headers.api_key]
name = "key"
value = "xxxx"

[rates]

[rates.from]
path = "api/stream/index_v1"
method = "Post"
check_path = "$.result.percentages[0].price"
reconcile_path = "$.result.interval.endTime"

[rates.from.params]
args = '{"indexCode": "KK_BRR_BTCUSD"}'

[rates.target]
path = "api/stream/index_v1"
method = "Post"
check_path = "$.result.percentages[0].price"
reconcile_path = "$.result.interval.endTime"

[rates.target.params]
args = '{"indexCode": "KK_BRR_ETHUSD"}'
