[origin_base]
url = "http://127.0.0.1:10000"
[origin_base.method]
type = "grpc"

[bench_base]
url = "http://127.0.0.1:10000"
[bench_base.method]
type = "grpc"

[savonnette]

[savonnette.from]
path = "impliedvolatility.Savon/ComputeTradeWeightedImpliedVol"
method = "Post"
check_path = "$.implied_vols[0].implied_volatility"

[savonnette.from.params]
args = '{"prices":[{"timestamp":"2022-03-01T00:58:00.000Z","strike":35000,"expiry":"2022-06-24T00:00:00.000Z","option_type":"P","price":0.0625,"forward_log_moneyness":-0.1335313926,"time_to_expiry":0.3149579815,"spot":40000,"forward":40000},{"timestamp":"2022-03-01T00:58:00.000Z","strike":70000,"expiry":"2022-09-30T00:00:00.000Z","price":0.0666,"forward_log_moneyness":0.5596157879,"time_to_expiry":0.5834511071,"spot":40000,"forward":40000}],"skip_spot":false,"min_weight":1,"max_weight":10,"tick_size":0.0005,"tick_nb_threshold":5,"start_time":"2022-03-01T00:00:00.000Z","end_time":"2022-03-01T01:00:00.000Z"}'

[savonnette.target]
path = "impliedvolatility.Savon/ComputeTradeWeightedImpliedVol"
method = "Post"
check_path = "$.implied_vols[0].implied_volatility"
protoset_path = ""

[savonnette.target.params]
args = '{"prices":[{"timestamp":"2022-03-01T00:58:00.000Z","strike":35000,"expiry":"2022-06-24T00:00:00.000Z","option_type":"P","price":0.0625,"forward_log_moneyness":-0.1335313926,"time_to_expiry":0.3149579815,"spot":40000,"forward":40000},{"timestamp":"2022-03-01T00:58:00.000Z","strike":70000,"expiry":"2022-09-30T00:00:00.000Z","price":0.0666,"forward_log_moneyness":0.5596157879,"time_to_expiry":0.5834511071,"spot":40000,"forward":40000}],"skip_spot":false,"min_weight":1,"max_weight":10,"tick_size":0.0005,"tick_nb_threshold":5,"start_time":"2022-03-01T00:00:00.000Z","end_time":"2022-03-01T01:00:00.000Z"}'
