# Stream need to be set at the top level.
stream = true

[origin_base]
url = "https://gateway-v0-http.kaiko.ovh"
[origin_base.method]
type = "http"

[bench_base]
url = "https://gateway-v0-grpc.kaiko.ovh"
[bench_base.method]
type = "grpc"
protoset_path = "<path to protoset file>"

[headers.origin.api_key]
name = "key"
value = "xxxx"

[headers.bench.api_key]
name = "Authorization"
value = "Bearer xxxx"

[rates]

[rates.from]
path = "api/stream/index_v1"
method = "Post"
check_path = "$.result.percentages[0].price"
reconcile_path = "$.result.interval.endTime"

[rates.from.params]
args = '{"indexCode": "KK_BRR_BTCUSD"}'

[rates.target]
path = "kaikosdk.StreamIndexServiceV1/Subscribe"
method = "Post"
check_path = "$.percentages[0].price"
reconcile_path = "$.interval.endTime"

[rates.target.params]
args = '{"indexCode": "KK_BRR_ETHUSD"}'
