exclude = ["bench.toml", "bench_stream.toml"]

[formatting]
align_comments = true
align_entries = false
array_auto_collapse = false
array_auto_expand = true
array_trailing_comma = true
column_width = 100
compact_arrays = true
compact_inline_tables = false
indent_string = "    "
reorder_keys = false

[[rule]]
keys = ["*"]
[rule.formatting]
reorder_keys = true
